theme: jekyll-theme-cayman
title: Exploring the Campaign Donations of Universities
description: Sylvia Frank, Emily Lachtara, Tony Ni
author: Sylvia Frank, Emily Lachtara, Tony Ni
name: "Sylvia Frank, Emily Lachtara, Tony Ni"
title-img: /https://www.insidehighered.com/views/2019/01/23/partisan-politics-keeps-those-political-left-seeing-threats-free-speech-opinion/

